const TandC = () => {
  // created with https://www.wonder.legal/uk/creation-modele/website-terms-and-conditions-of-use-57
  return (<>
  <div className='backgroundImageWrapper' style={{backgroundColor:"black"}}>
  </div>
  <div style={{backgroundColor:"#EEEEEE", padding:"10px", borderRadius:"10px", margin:"5px"}}>
    <p style={{textAlign: "center"}}><span style={{textDecoration: "underline"}}><strong><span id="span_id_website_operator">THIS WAY OF LIFE FILM</span></strong></span></p>
    <p style={{textAlign: "center"}}><span style={{textDecoration: "underline"}}><strong>Website Terms and Conditions of Use</strong></span></p>

    <p><strong>1. Our Terms</strong></p>
    <p style={{paddingLeft: "30px"}}><strong>A.</strong> These Terms explain how you may use this website (the Site), which is provided by us free of charge.</p>
    <p style={{paddingLeft: "30px"}}><strong>B.</strong> References in these Terms to the Site includes the following websites and all associated subdomains and web pages:</p>
    <p style={{paddingLeft: "60px"}}><span id="span_id_sites">twol82.com</span></p>
    <p style={{paddingLeft: "30px"}}><strong>C.</strong> You should read these Terms carefully before using the Site.</p>
    <p style={{paddingLeft: "30px"}}><strong>D.</strong> By accessing or using the Site or otherwise indicating your consent, you agree to be bound by these Terms and the documents referred to in them.</p>
    <p style={{paddingLeft: "30px"}}><strong>E.</strong> If you do not agree with or accept any of these Terms, you should stop using the Site immediately.</p>
    <p style={{paddingLeft: "30px"}}><strong>F.</strong> If you have any questions about the Site, please contact us by using the following e-mail address: <span id="span_id_email">Martin@twol82.com</span>. </p>
    <p style={{paddingLeft: "30px"}}><strong>G.</strong> Definitions:</p>
    <p style={{paddingLeft: "60px", textAlign: "left"}}><strong>I.</strong> "Content" means any text, images, video, audio or other multimedia content, software or other information or material submitted to or on the Site,</p>
    <p style={{paddingLeft: "60px", textAlign: "left"}}><strong>II.</strong> "Terms" means these terms and conditions of use as updated from time to time,</p>
    <p style={{paddingLeft: "60px", textAlign: "left"}}><strong>III.</strong> "Intellectual property rights" means rights such as copyright, trade marks, domain names, design rights, database rights, patents and all other intellectual property rights of any kind whether or not they are registered or unregistered (anywhere in the world),</p>
    <p style={{paddingLeft: "60px", textAlign: "left"}}><strong>IV.</strong> "Unwanted Submission" has the meaning given to it in the section entitled "submitting information to the site",   </p>
    <p style={{paddingLeft: "60px", textAlign: "left"}}><strong> V.</strong> "Privacy policy" means the policy (<span id="span_id_privacy">https://twol82.com/#/PrivacyPolicy</span>), which governs how we process any personal data collected from you,</p>
    <p style={{paddingLeft: "60px", textAlign: "left"}}><strong>VI.</strong> "Site" means the following websites and all associated subdomains and web pages:</p>
    <p style={{paddingLeft: "90px"}}><span id="span_id_sites">twol82.com</span>,</p>
    <p style={{paddingLeft: "60px"}}><strong>VII. </strong>"We, us or our" means <span id="span_id_website_operator">THIS WAY OF LIFE FILM</span> whose office is at:</p>
    <p style={{paddingLeft: "90px"}}><span id="span_id_operator_address">Contact Martin@twol82.com for details.</span> </p>
    <p style={{paddingLeft: "60px", textAlign: "left"}}>References to us in these Terms also includes any group companies which we may have from time to time,</p>
    <p style={{paddingLeft: "60px", textAlign: "left"}}><strong>VIII.</strong> "You or your" means the person accessing or using the Site or its Content.   </p>
    <p style={{paddingLeft: "30px"}}><strong>H.</strong> Your use of the Site means that you must also comply (where applicable) with our: </p>
    <p style={{paddingLeft: "60px"}}><strong>I.</strong> Privacy policy </p>
    <p style={{paddingLeft: "30px"}}><strong>I.</strong> We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time. It is your responsibility to check these Terms of Use periodically for changes. Your continued use of the Site following the posting of changes will mean that you accept and agree to the changes.<br /><br /></p>
    <p><strong>2. Using the Site</strong></p>
    <p style={{paddingLeft: "30px"}}><strong>A.</strong> The Site is for your personal, non-commercial and non-exclusive use only. As long as you comply with these Terms of Use <span id="span_id_website_operator">THIS WAY OF LIFE FILM</span> grants you a personal, non-exclusive, non-transferable, and non-commercial limited privilege to enter and use the Site.</p>
    <p style={{paddingLeft: "30px"}}><strong>B.</strong> You may not use any "page-scraper", "robot", "spider", "deep-link" or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, copy, acquire, or monitor any part of the Site, or in any way reproduce or circumvent the navigational structure or presentation of the Site or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Site.</p>
    <p style={{paddingLeft: "30px"}}><strong>C.</strong> You may not attempt to gain unauthorised access to any part or feature of the Site, or any other systems or networks connected to the Site or to any of our servers, or to any of the services offered on or through the Site, by password "mining", hacking or any other illegitimate means.</p>
    <p style={{paddingLeft: "30px"}}><strong>D.</strong> You may not scan, probe or test the vulnerability of the Site or any network connected to the Site, nor breach the security or authentication measures on the Site or any network connected to the Site.</p>
    <p style={{paddingLeft: "30px"}}><strong>E.</strong> You may not reverse look-up, trace or seek to trace any information on any other user of or visitor to the Site, or any other customer of ours, to its source, or exploit the Site or any service or information made available or offered by or through the Site, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than your own information, as provided for by the Site.</p>
    <p style={{paddingLeft: "30px"}}><strong>F.</strong> You agree that you will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Site or our systems or networks, or any systems or networks connected to the Site.</p>
    <p style={{paddingLeft: "30px"}}><strong>G.</strong> You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Site or any transaction being conducted on the Site, or with any other person's use of the Site.</p>
    <p style={{paddingLeft: "30px"}}><strong>H.</strong> You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal you send to us on or through the Site or any service offered on or through the Site. You may not pretend that you are, or that you represent, someone else, or impersonate any other individual or entity.</p>
    <p style={{paddingLeft: "30px"}}><strong>I.</strong> You may not use the Site or any Content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes our rights or those of others.</p>
    <p style={{paddingLeft: "30px"}}><strong>J.</strong> The Site is intended for use only by those who can access it from within the UK. If you choose to access the Site from locations outside the UK, you are responsible for compliance with local laws where they are applicable.</p>
    <p style={{paddingLeft: "30px"}}><strong>K.</strong> You agree that you are solely responsible for:</p>
    <p style={{paddingLeft: "60px"}}><strong>I.</strong> all costs and expenses you may incur in relation to your use of the Site, and</p>
    <p style={{paddingLeft: "60px"}}><strong>II.</strong> keeping your password and any other account details which may be necessary or required confidential. </p>
    <p style={{paddingLeft: "30px"}}><strong>L.</strong> We seek to make the Site as accessible as possible. If you have any difficulties using the Site, please contact us at <span id="span_id_email">Martin@twol82.com</span>.  </p>
    <p style={{paddingLeft: "30px"}}><strong>M.</strong> We may prevent or suspend your access to the Site if you do not comply with any part of these Terms, any terms or policies to which they refer or any applicable law.</p>

    <p><strong>3. Ownership, use and intellectual property rights</strong></p>
    <p style={{paddingLeft: "30px"}}><strong>A.</strong> This Site and all intellectual property rights in it, including but not limited to any Content, are owned by us, our licensors or both (as applicable). We and our licensors reserve all of our and their rights in any intellectual property in connection with these Terms. This means, for example, that we and they remain owners of them and free to use them as we and they see fit.</p>
    <p style={{paddingLeft: "30px"}}><strong>B.</strong> Nothing in these Terms grants you any legal rights in the Site other than as necessary to enable you to lawfully access the Site as intended and authorized by us. You agree not to adjust to try to circumvent or delete any notices contained on the Site (including any intellectual property notices) and in particular in any digital rights or other security technology embedded or contained within the Site. </p>
    <p style={{paddingLeft: "30px"}}><strong> C. </strong>The use of any trade marks on the Site is strictly prohibited unless you have our prior written permission.<br /><br /></p>
    <p><strong>4. Submitting information to the Site</strong></p>
    <p style={{paddingLeft: "30px"}}><strong>A.</strong> While we try to make sure that the Site is secure, we cannot guarantee the security of any information that you supply to us. We therefore cannot guarantee that it will be kept confidential. For that reason, you should not submit any patentable ideas or patent applications, advertising or marketing suggestions, prototypes, or any other information that you regard as confidential, commercially sensitive or valuable (Unwanted Submissions) to the Site. While we value your feedback, you agree not to submit any Unwanted Submissions.</p>
    <p style={{paddingLeft: "30px"}}><strong>B.</strong> We may use any Unwanted Submissions as we see reasonably fit on a free-of-charge basis (bear in mind that we have no way of knowing whether such information is confidential, commercially sensitive or valuable because we do not monitor the Site to check for these matters). Therefore, we will not be legally responsible for keeping any Unwanted Submissions confidential nor will we be legally responsible to you or anybody else for any use of such Unwanted Submissions.<br /><br /></p>
    <p><strong>5. Accuracy of information and availability of the Site</strong></p>
    <p style={{paddingLeft: "30px"}}><strong>A.</strong> While we try to make sure that the Site is accurate, up-to-date and free from bugs, we cannot guarantee that it will be. Furthermore, we cannot guarantee that the Site will be fit or suitable for any purpose. Any reliance that you may place on the information on this Site is at your own risk.</p>
    <p style={{paddingLeft: "30px"}}><strong>B.</strong> We may suspend or terminate operation of the Site at any time as we see fit. </p>
    <p style={{paddingLeft: "30px"}}><strong>C.</strong> Content is provided for your general information purposes only and to inform you about us and our products and news, features, services and other websites that may be of interest. It does not constitute technical, financial or legal advice or any other type of advice and should not be relied on for any purposes.</p>
    <p style={{paddingLeft: "30px"}}><strong>D.</strong> While we try to make sure that the Site is available for your use, we do not promise that the Site is available at all times nor do we promise the uninterrupted use by you of the Site.<br /><br /></p>
    <p><strong>6. Hyperlinks and third party sites</strong></p>
    <p style={{paddingLeft: "30px"}}>The Site may contain hyperlinks or references to third party websites other than the Site. Any such hyperlinks or references are provided for your convenience only. We have no control over third party websites and accept no legal responsibility for any content, material or information contained in them. The display of any hyperlink and reference to any third party website does not mean that we endorse that third party's website, products or services. Your use of a third party site may be governed by the terms and conditions of that third party site.<br /><br /></p>
    <p><strong>7. Events beyond our control</strong></p>
    <p style={{paddingLeft: "30px"}}>We shall have no liability to you for any breach of these Terms caused by any event or circumstance beyond our reasonable control including, but not limited to, strikes, lock-outs or other industrial disputes, breakdown of systems or network access, or flood, fire, explosion or accident.<br /><br /></p>
    <p><strong>8. Rights of third parties</strong></p>
    <p style={{paddingLeft: "30px"}}>No one other than a party to these Terms has any right to enforce any of these Terms.<br /><br /></p>
    <p><strong>9. Disputes</strong></p>
    <p style={{paddingLeft: "30px"}}><strong>A.</strong> We will try to resolve any disputes or complaints you may have quickly and efficiently.</p>
    <p style={{paddingLeft: "30px"}}><strong>B.</strong> If you are unhappy with us please contact us as soon as possible. </p>
    <p style={{paddingLeft: "30px"}}><strong>C.</strong> We shall always endeavour to resolve any problem or issue that may arise between you and us as efficiently and smoothly as possible, however where this is not possible and you wish to raise a formal complaint, we can be contacted in the following ways:</p>
    <p style={{paddingLeft: "60px"}}><strong>I.</strong> by post at the following address: </p>
    <p style={{paddingLeft: "90px"}}><span id="span_id_operator_address">Contact Martin@twol82.com for details.</span></p>
    <p style={{paddingLeft: "60px"}}><strong>II.</strong> by email using the following email address: <span id="span_id_complaints_email">Martin@twol82.com</span></p>
    <p style={{paddingLeft: "30px"}}><strong>D.</strong> We shall always aim to remedy your complain immediately. Where such remedy is not available immediately we shall acknowledge receipt of your complaint in writing within <span id="span_id_days_acknowledge">14</span> working days of the complaint being made. Where your complaint concerns services provided by us through the Site we shall aim to give you our response within <span id="span_id_days_response">30</span> days after the complaint has been received by us. Where the complaint relates to exceptional circumstances which are beyond our control, such circumstances include but are not limited to: internet service provider failure, power failure, acts of God, pandemic, epidemic, fire, flood, droughts, storms, civil unrest, collapse of buildings, earthquakes, explosion, accidents, acts of war or terrorism, or any law or actions taken by government or public authorities or any other event that is beyond our control we shall aim to respond to your complaint within a maximum of <span id="span_id_working_days">60</span> working days of the complaint being made. If your complaint does not relate to any service provided by us through the Site we shall aim to provide a response to your complaint within <span id="span_id_number_weeks">4</span> weeks of the complaint being made and where we shall take longer than <span id="span_id_number_weeks">4</span> weeks we shall inform you of this. </p>
    <p style={{paddingLeft: "30px"}}><strong>E.</strong> If you and we cannot resolve a dispute using our complaint handling procedure, we will:</p>
    <p style={{paddingLeft: "60px"}}><strong>I.</strong> let you know that we cannot settle the dispute with you, and</p>
    <p style={{paddingLeft: "60px"}}><strong>II.</strong> consider the need for Alternative Dispute Resolution and, if considered necessary, provide you with information about any alternative dispute resolution provider we deem appropriate to deal with your complaint.  </p>
    <p style={{paddingLeft: "30px"}}><strong>F.</strong> If you want to take court proceedings, the relevant courts of the United Kingdom will have exclusive jurisdiction in relation to these Terms.</p>
    <p style={{paddingLeft: "30px"}}><strong>G.</strong> Relevant United Kingdom law will apply to these Terms.<br /><br /></p>
    <p>These Terms and Conditions of Use are up to date as of: <span>10/03/2023</span>.</p>
  </div>
  </>);
};

export default TandC;
